use std::fmt;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum TemplateKind {
    HelloWorld,
    Nep17Token,
    Nep11Nft,
    StorageMap,
    OracleConsumer,
    UpgradeableAdmin,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TemplateOptions {
    pub contract_name: String,
    pub symbol: String,
    pub decimals: u8,
    pub author: String,
}

impl TemplateOptions {
    pub fn new(contract_name: impl Into<String>) -> Self {
        let contract_name = contract_name.into();
        let symbol = contract_name
            .chars()
            .filter(|ch| ch.is_ascii_alphanumeric())
            .take(8)
            .collect::<String>()
            .to_uppercase();
        Self {
            contract_name,
            symbol: if symbol.is_empty() {
                "TOKEN".into()
            } else {
                symbol
            },
            decimals: 0,
            author: "neo-lang".into(),
        }
    }

    pub fn symbol(mut self, symbol: impl Into<String>) -> Self {
        self.symbol = symbol.into();
        self
    }

    pub fn decimals(mut self, decimals: u8) -> Self {
        self.decimals = decimals;
        self
    }

    pub fn author(mut self, author: impl Into<String>) -> Self {
        self.author = author.into();
        self
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RenderedTemplate {
    pub kind: TemplateKind,
    pub files: Vec<TemplateFile>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TemplateFile {
    pub path: String,
    pub contents: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TemplateError {
    EmptyContractName,
}

impl fmt::Display for TemplateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TemplateError::EmptyContractName => write!(f, "contract name must not be empty"),
        }
    }
}

pub fn render_template(
    kind: TemplateKind,
    options: &TemplateOptions,
) -> Result<RenderedTemplate, TemplateError> {
    if options.contract_name.trim().is_empty() {
        return Err(TemplateError::EmptyContractName);
    }
    let source = match kind {
        TemplateKind::HelloWorld => render(HELLO_WORLD, options),
        TemplateKind::Nep17Token => render(NEP17_TOKEN, options),
        TemplateKind::Nep11Nft => render(NEP11_NFT, options),
        TemplateKind::StorageMap => render(STORAGE_MAP, options),
        TemplateKind::OracleConsumer => render(ORACLE_CONSUMER, options),
        TemplateKind::UpgradeableAdmin => render(UPGRADEABLE_ADMIN, options),
    };
    Ok(RenderedTemplate {
        kind,
        files: vec![
            TemplateFile {
                path: format!("{}.neo", options.contract_name),
                contents: source,
            },
            TemplateFile {
                path: "README.md".into(),
                contents: readme(kind, options),
            },
        ],
    })
}

fn render(source: &str, options: &TemplateOptions) -> String {
    source
        .replace("{{contract_name}}", &options.contract_name)
        .replace("{{symbol}}", &options.symbol)
        .replace("{{decimals}}", &options.decimals.to_string())
        .replace("{{author}}", &options.author)
}

fn readme(kind: TemplateKind, options: &TemplateOptions) -> String {
    let label = match kind {
        TemplateKind::HelloWorld => "Hello World contract",
        TemplateKind::Nep17Token => "NEP-17 token contract",
        TemplateKind::Nep11Nft => "NEP-11 NFT contract",
        TemplateKind::StorageMap => "storage map contract",
        TemplateKind::OracleConsumer => "oracle consumer contract",
        TemplateKind::UpgradeableAdmin => "upgradeable admin contract",
    };
    format!(
        "# {}\n\nGenerated by neo-devpack as a {} starting point.\n",
        options.contract_name, label
    )
}

const HELLO_WORLD: &str = r#"#[author("{{author}}")]
#[version("0.1.0")]
#[description("A minimal neo-lang contract.")]
contract {{contract_name}} {
    #[safe]
    string sayHello(string name) {
        return "Hello, " + name;
    }
}
"#;

const NEP17_TOKEN: &str = r#"#[author("{{author}}")]
#[version("0.1.0")]
#[description("A NEP-17 token contract.")]
#[supportedStandards("NEP-17")]
contract {{contract_name}} {
    map[hash160, int] balances;
    int supply = 0;

    event Transfer(hash160 from, hash160 to, int amount);

    #[safe]
    int totalSupply() {
        return self.supply;
    }

    #[safe]
    string symbol() {
        return "{{symbol}}";
    }

    #[safe]
    int decimals() {
        return {{decimals}};
    }

    #[safe]
    int balanceOf(hash160 account) {
        return self.balances[account];
    }

    bool transfer(hash160 from, hash160 to, int amount, any data) {
        assert(amount >= 0, "amount must be non-negative");
        if amount == 0 {
            emit Transfer(from, to, amount);
            return true;
        }

        var fromBalance = self.balances[from];
        if fromBalance < amount {
            return false;
        }

        self.balances[from] = fromBalance - amount;
        self.balances[to] = self.balances[to] + amount;
        emit Transfer(from, to, amount);
        return true;
    }
}
"#;

const NEP11_NFT: &str = r#"#[author("{{author}}")]
#[version("0.1.0")]
#[description("A NEP-11 NFT contract.")]
#[supportedStandards("NEP-11")]
contract {{contract_name}} {
    map[string, hash160] owners;
    map[string, string] names;
    int supply = 0;

    event Transfer(hash160 from, hash160 to, int amount, string tokenId);

    #[safe]
    string symbol() {
        return "{{symbol}}";
    }

    #[safe]
    int decimals() {
        return 0;
    }

    #[safe]
    int totalSupply() {
        return self.supply;
    }

    #[safe]
    any tokens() {
        return null;
    }

    #[safe]
    int balanceOf(hash160 owner) {
        return 0;
    }

    #[safe]
    any tokensOf(hash160 owner) {
        return null;
    }

    #[safe]
    hash160 ownerOf(string tokenId) {
        return self.owners[tokenId];
    }

    #[safe]
    map[string, string] properties(string tokenId) {
        return map[string, string] {
            "name": self.names[tokenId]
        };
    }

    bool transfer(hash160 to, string tokenId, any data) {
        var owner = self.owners[tokenId];
        self.owners[tokenId] = to;
        emit Transfer(owner, to, 1, tokenId);
        return true;
    }
}
"#;

const STORAGE_MAP: &str = r#"#[author("{{author}}")]
#[version("0.1.0")]
#[description("A typed storage-map contract.")]
contract {{contract_name}} {
    map[string, string] records;

    void put(string key, string value) {
        self.records[key] = value;
    }

    #[safe]
    string get(string key) {
        return self.records[key];
    }

    void remove(string key) {
        self.records.remove(key);
    }
}
"#;

const ORACLE_CONSUMER: &str = r#"#[author("{{author}}")]
#[version("0.1.0")]
#[description("An oracle-consumer starting point.")]
contract {{contract_name}} {
    string lastResponse = "";

    void request(string url) {
        runtime.log("oracle request queued");
        runtime.notify("OracleRequest", any[] { url });
    }

    void oracleCallback(string url, string response) {
        self.lastResponse = response;
        runtime.notify("OracleResponse", any[] { url, response });
    }

    #[safe]
    string latest() {
        return self.lastResponse;
    }
}
"#;

const UPGRADEABLE_ADMIN: &str = r#"#[author("{{author}}")]
#[version("0.1.0")]
#[description("An admin-gated upgradeable contract.")]
contract {{contract_name}} {
    hash160 owner;

    #[safe]
    hash160 getOwner() {
        return self.owner;
    }

    bool verify() {
        return runtime.checkWitness(self.owner);
    }

    void update(buffer nefFile, string manifest) {
        assert(runtime.checkWitness(self.owner), "missing owner witness");
        runtime.log("update requested");
    }
}
"#;
